"""Acceptance tests for Decision Logs D-90, D-91, D-93, and D-94.

These tests inspect two generated-project artifacts that are already exposed by the acceptance
harness: the embedded identification QML source and the standard QGIS ``.qgs`` layer-tree XML.
They do not attempt to launch QField or construct a QGIS application in the test process.
"""
from __future__ import annotations

import re
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

from .conftest import SURVEY_TYPE_SCHEMAS, make_base_config

pytestmark = pytest.mark.qgis

FAKE_PLANTNET_KEY = "ACCEPTANCE-D90-FAKE-PLANTNET-KEY"
FAKE_VWORLD_KEY = "ACCEPTANCE-D91-FAKE-VWORLD-KEY"
SMALL_BBOX = {"min_lon": 127.000, "min_lat": 37.000, "max_lon": 127.010, "max_lat": 37.010}
PROBABILITY_LOOKUP_RELPATH = "reference/rasters/occurrence_probability_multiband.tif"
IDENTIFICATION_WIDGETS = (
    ("Type 1", "simple_inventory", "inventory_observation"),
    ("Type 2", "temporary_plots", "observation"),
    ("Type 3", "permanent_plots", "observation"),
)


def _identification_result(acceptance_api, tmp_path, survey_type: str, *, consent: bool = False):
    config = make_base_config(survey_type)
    config["identification_enabled"] = True
    config["plantnet"] = {
        "api_key": FAKE_PLANTNET_KEY,
        "consent_accepted": consent,
        "remember_key": False,
    }
    return acceptance_api.build_project(config, str(tmp_path / f"ident_{survey_type}_{consent}"))


def _widget_qml(acceptance_api, result: dict, layer_name: str) -> str:
    report = acceptance_api.inspect_identification_widget(result["project_dir"], layer_name)
    assert report["qml_widget_field_found"] is True, report
    source = report.get("qml_code", "")
    assert source.strip(), "the generated identification widget must expose non-empty QML source"
    return source


def _identify_button_handler(source: str) -> str:
    """Return the generated QML Identify button's onClicked body.

    The embedded QML is generated by this project and the button has a stable id mandated by the
    existing identification-widget artifact.  Limiting the extraction to the first closing brace
    of this handler avoids making assertions about unrelated candidate/manual-entry handlers.
    """
    button = re.search(r"\bid\s*:\s*qpbIdentifyButton\b", source)
    assert button, "expected an Identify button id in the embedded widget QML"
    clicked = source.find("onClicked:", button.end())
    assert clicked >= 0, "expected the Identify button to have an onClicked handler"
    end = source.find("\n        }", clicked)
    assert end >= 0, "could not delimit the Identify button's onClicked handler"
    return source[clicked:end]


def _identify_button_source(source: str) -> str:
    """Return the generated photo-identification button's local QML source."""
    button = re.search(r"\bid\s*:\s*qpbIdentifyButton\b[\s\S]{0,500}", source)
    assert button, "expected a generated photo-identification button"
    return button.group(0)


def _non_declaration_invocations(source: str, function_name: str) -> list[str]:
    """Return source snippets for calls, excluding the function declaration itself."""
    calls = []
    declaration = re.search(rf"\bfunction\s+{re.escape(function_name)}\s*\(", source)
    for match in re.finditer(rf"\b{re.escape(function_name)}\s*\(", source):
        if declaration and match.start() == declaration.end() - len(match.group(0)):
            continue
        calls.append(match.group(0))
    return calls


@pytest.mark.parametrize(
    "type_name,survey_type,layer_name",
    IDENTIFICATION_WIDGETS,
)
def test_ac133_type_1_to_3_identify_click_starts_without_application_popup(
    acceptance_api, tmp_path, type_name, survey_type, layer_name
):
    """AC-QPB-133: every generated Type 1–3 photo-identification click is immediate."""
    result = _identification_result(acceptance_api, tmp_path, survey_type)
    assert result["success"], result.get("error_message")
    source = _widget_qml(acceptance_api, result, layer_name)
    button = _identify_button_source(source)
    handler = _identify_button_handler(source)

    assert 'text: "사진으로 동정하기"' in button, (
        f"AC-QPB-133 (D-93): {type_name}'s generated qpbIdentifyButton must be the "
        "`사진으로 동정하기` control"
    )
    assert re.search(r"\bqpbRunIdentification\s*\(\s*\)", handler), (
        f"AC-QPB-133/FR-QPB-101 (D-93): {type_name} Identify onClicked must start "
        "identification directly"
    )
    assert "qpbConsentDialog" not in handler
    assert not re.search(r"\b(open|show)\s*\(", handler), (
        "AC-QPB-133: the Identify click must not open an application-owned intermediate dialog"
    )
    assert not re.search(r"\bDialog\s*\{", source), (
        f"AC-QPB-133: the {type_name} identification widget must not author a consent/OK Dialog"
    )
    assert "qpbConsentDialog" not in source


@pytest.mark.parametrize(
    "type_name,survey_type,layer_name",
    IDENTIFICATION_WIDGETS,
)
def test_ac134_type_1_to_3_identify_is_manual_only_and_attachment_does_not_auto_identify(
    acceptance_api, tmp_path, type_name, survey_type, layer_name
):
    """AC-QPB-134: only the explicit Type 1–3 Identify action starts the workflow.

    A generated widget has one invocation of ``qpbRunIdentification`` outside its function
    declaration: the explicit button action.  This is a deterministic structural proxy for the
    unchanged FR-QPB-102 rule that attaching a photo alone must not invoke identification.
    """
    result = _identification_result(acceptance_api, tmp_path, survey_type)
    assert result["success"], result.get("error_message")
    source = _widget_qml(acceptance_api, result, layer_name)
    handler = _identify_button_handler(source)

    calls = _non_declaration_invocations(source, "qpbRunIdentification")
    assert len(calls) == 1, (
        "AC-QPB-134/FR-QPB-102: identification must not be invoked automatically by photo "
        f"attachment or another hidden trigger for {type_name}; found {len(calls)} runtime "
        "call(s)"
    )
    assert re.search(r"\bqpbRunIdentification\s*\(\s*\)", handler)
    assert "onAccepted" not in handler


@pytest.mark.parametrize("consent", [False, True], ids=["embedding-declined", "embedding-accepted"])
@pytest.mark.parametrize(
    "type_name,survey_type,layer_name",
    IDENTIFICATION_WIDGETS,
)
def test_ac134_type_1_to_3_identify_behavior_does_not_replace_separate_key_embedding_consent(
    acceptance_api, tmp_path, type_name, survey_type, layer_name, consent
):
    """AC-QPB-134/FR-QPB-115/116: field action and desktop key consent stay distinct."""
    result = _identification_result(acceptance_api, tmp_path, survey_type, consent=consent)
    assert result["success"], result.get("error_message")
    source = _widget_qml(acceptance_api, result, layer_name)
    handler = _identify_button_handler(source)
    assert re.search(r"qpbRunIdentification\s*\(\s*\)", handler), (
        f"AC-QPB-134: {type_name} immediate field-button behavior must not depend on "
        "desktop Pl@ntNet key-embedding consent"
    )
    assert "qpbConsentDialog" not in source

    qgs_text = Path(result["qgs_path"]).read_text(encoding="utf-8")
    if consent:
        assert FAKE_PLANTNET_KEY in qgs_text
    else:
        assert FAKE_PLANTNET_KEY not in qgs_text
    project_dir = Path(result["project_dir"])
    qgs_path = Path(result["qgs_path"])
    for path in project_dir.rglob("*"):
        if path.is_file() and path != qgs_path:
            assert FAKE_PLANTNET_KEY.encode() not in path.read_bytes()


def _layer_tree_groups(qgs_path: str) -> dict[str, ET.Element]:
    root = ET.parse(qgs_path).getroot()
    layer_tree = root.find("layer-tree-group")
    assert layer_tree is not None, f"expected a root layer-tree-group in {qgs_path}"
    return {
        group.get("name"): group
        for group in layer_tree.findall("layer-tree-group")
        if group.get("name") in {"Survey data", "Reference", "Basemap"}
    }


def _map_layer_datasources(root: ET.Element) -> dict[str, str]:
    """Map layer-tree IDs to their generated-project datasource identities."""
    return {
        layer_id: datasource
        for map_layer in root.findall("./projectlayers/maplayer")
        if (layer_id := map_layer.findtext("id"))
        if (datasource := map_layer.findtext("datasource"))
    }


def _assert_initial_layer_visibility(qgs_path: str) -> tuple[dict[str, list[str]], int]:
    root = ET.parse(qgs_path).getroot()
    layer_tree = root.find("layer-tree-group")
    assert layer_tree is not None, f"expected a root layer-tree-group in {qgs_path}"
    groups = {
        group.get("name"): group
        for group in layer_tree.findall("layer-tree-group")
        if group.get("name") in {"Survey data", "Reference", "Basemap"}
    }
    assert set(groups) == {"Survey data", "Reference", "Basemap"}, (
        "AC-QPB-135/FR-QPB-136 (D-94): expected all required root layer-tree groups, found "
        f"{sorted(groups)}"
    )
    observed: dict[str, list[str]] = {}
    checked_values = {"Qt::Checked", "1", "true", "True"}
    datasources = _map_layer_datasources(root)
    probability_lookup_count = 0
    for name, group in groups.items():
        nodes = group.findall(".//layer-tree-layer")
        observed[name] = [node.get("name", "") for node in nodes]
        for node in nodes:
            datasource = datasources.get(node.get("id", ""), "").replace("\\", "/")
            is_probability_lookup = datasource.endswith(PROBABILITY_LOOKUP_RELPATH)
            if is_probability_lookup:
                probability_lookup_count += 1
                assert name == "Reference", (
                    "AC-QPB-135/D-94: the occurrence-probability lookup raster must remain "
                    f"registered under Reference, not {name!r}"
                )
                assert node.get("checked") not in checked_values, (
                    "AC-QPB-135/FR-QPB-136 (D-94): the registered "
                    "occurrence_probability_multiband lookup raster must be default-hidden; "
                    f"checked={node.get('checked')!r}"
                )
            else:
                assert node.get("checked") in checked_values, (
                    "AC-QPB-135/FR-QPB-136 (D-94): every Survey data, Basemap, and non-lookup "
                    "Reference layer node must be checked/visible; "
                    f"group={name!r}, layer={node.get('name')!r}, checked={node.get('checked')!r}"
                )
    assert observed["Survey data"], "expected at least one generated Survey data layer"
    return observed, probability_lookup_count


def _visibility_config(survey_type: str, basemap_mode: str) -> dict:
    config = make_base_config(survey_type)
    config["identification_enabled"] = True
    if basemap_mode == "online":
        config["basemap"] = {
            "mode": "online",
            "vworld_api_key": FAKE_VWORLD_KEY,
            "layer": "Base",
            "consent_accepted": True,
            "remember_key": False,
        }
    elif basemap_mode == "offline":
        config["basemap"] = {
            "mode": "offline",
            "vworld_api_key": FAKE_VWORLD_KEY,
            "layer": "Base",
            "bbox": SMALL_BBOX,
            "min_zoom": 10,
            "max_zoom": 10,
            "tile_source": {"fake": {"mode": "success", "tile_bytes": 4000}},
        }
    return config


@pytest.mark.parametrize("survey_type", list(SURVEY_TYPE_SCHEMAS))
@pytest.mark.parametrize("basemap_mode", ["none", "online", "offline"])
def test_ac135_initial_layers_are_visible_except_registered_probability_lookup_on_untouched_reopen(
    acceptance_api, tmp_path, survey_type, basemap_mode
):
    """AC-QPB-135: only the registered probability lookup is hidden on first/reopened open."""
    config = _visibility_config(survey_type, basemap_mode)
    out_dir = tmp_path / f"visibility_{survey_type}_{basemap_mode}"
    result = acceptance_api.build_project(config, str(out_dir))
    assert result["success"], result.get("error_message")

    qgs_path = Path(result["qgs_path"])
    before = qgs_path.read_bytes()
    first_open_layers, first_open_lookup_count = _assert_initial_layer_visibility(str(qgs_path))
    if survey_type != "vegetation_mapping":
        assert first_open_lookup_count == 1, (
            "AC-QPB-135/D-94: Types 1–3 with identification enabled must keep exactly one "
            "registered occurrence_probability_multiband lookup raster"
        )

    # validate_project() reopens the existing generated project through the same headless QGIS
    # path used elsewhere in this suite.  A fake online key may make the WMTS provider invalid;
    # that is unrelated to the layer-tree visibility state, so only the re-open call and the
    # untouched artifact are asserted here.
    reopened = acceptance_api.validate_project(result["project_dir"])
    assert isinstance(reopened, dict)
    assert qgs_path.read_bytes() == before, "reopening an untouched project must not rewrite it"
    reopened_layers, reopened_lookup_count = _assert_initial_layer_visibility(str(qgs_path))
    assert reopened_layers == first_open_layers
    assert reopened_lookup_count == first_open_lookup_count


def _offline_selection_config(layer: str | None, tile_mode: str = "success") -> dict:
    config = make_base_config("simple_inventory")
    config["basemap"] = {
        "mode": "offline",
        "vworld_api_key": FAKE_VWORLD_KEY,
        "layer": layer,
        "bbox": SMALL_BBOX,
        "min_zoom": 10,
        "max_zoom": 10,
        "tile_source": {"fake": {"mode": tile_mode, "tile_bytes": 4000}},
    }
    return config


def test_ac136_explicit_supported_offline_layer_is_recorded_in_mbtiles_and_project_source(
    acceptance_api, tmp_path
):
    """AC-QPB-136: a selected supported layer survives offline delivery without its key."""
    import sqlite3

    selected_layer = "Satellite"
    result = acceptance_api.build_project(
        _offline_selection_config(selected_layer), str(tmp_path / "selected-layer")
    )
    assert result["success"], result.get("error_message")

    mbtiles_path = next(Path(result["basemap_dir"]).glob("*.mbtiles"))
    with sqlite3.connect(str(mbtiles_path)) as connection:
        metadata = dict(connection.execute("SELECT name, value FROM metadata").fetchall())
        assert connection.execute("SELECT COUNT(*) FROM tiles").fetchone()[0] > 0
    metadata_text = "\n".join(str(value) for value in metadata.values())
    qgs_text = Path(result["qgs_path"]).read_text(encoding="utf-8")
    assert selected_layer in metadata_text, (
        "AC-QPB-136: MBTiles metadata must retain the explicitly selected VWorld layer identity"
    )
    assert selected_layer in qgs_text, (
        "AC-QPB-136: the generated offline project source must retain the selected layer identity"
    )
    assert FAKE_VWORLD_KEY not in metadata_text
    assert FAKE_VWORLD_KEY not in qgs_text


@pytest.mark.parametrize(
    "layer",
    [None, "", "RetiredUnsupported"],
    ids=["missing", "blank", "unsupported"],
)
def test_ac136_missing_blank_or_unsupported_offline_layer_fails_before_tile_retrieval_or_promotion(
    acceptance_api, tmp_path, layer
):
    """AC-QPB-136: selection validation wins over a fake provider failure and leaves no output."""
    output_dir = tmp_path / f"invalid-layer-{layer or 'missing'}"
    result = acceptance_api.build_project(
        _offline_selection_config(layer, tile_mode="quota_error"), str(output_dir)
    )
    assert result["success"] is False
    assert result.get("error_code") == "offline_layer_unavailable", result
    assert result.get("error_code") != "provider_quota", (
        "AC-QPB-136: invalid selection must fail before the tile source is invoked"
    )
    assert not output_dir.exists() or not any(output_dir.iterdir()), (
        "AC-QPB-136: invalid selection must not promote a partial offline project"
    )
