"""Korean field aliases on the generated project's real QGIS layers (Section 8.5, DR-QPB-071,
FR-QPB-119, AC-QPB-098; Decision Log D-56/D-57/D-58).

Covers:
- AC-QPB-098: given a generated project for any of the four survey types, when every layer's
  fields are inspected, then every field except a table's own UUID primary key (DR-QPB-071) has a
  non-empty, Korean-language alias set matching Section 8.5's now-fully-confirmed mapping — not
  the raw column name; and given the same layers, when a table's own UUID primary-key field
  specifically is inspected, then it has no alias set.

Per Decision Log D-57's own "Approval status" line, Section 8.5's Korean field-alias table is now
fully stakeholder-confirmed (D-57 confirmed all ten originally-flagged Medium-confidence terms
verbatim; D-58 confirmed the one remaining open sub-question — the Type-3 `plot_id` foreign-key
label's "고정" prefix — verbatim as well) and `test-designer`/`implementer` work may proceed
against DR-QPB-071/FR-QPB-119/Section 8.5/AC-QPB-098, notwithstanding that those requirements' own
inline text was not itself textually edited and still literally reads "draft proposal, not yet
stakeholder-approved." See this round's traceability file for the full analysis of why this is not
treated as a blocking ambiguity.

AC-QPB-098's own text also requires that a table's own UUID primary-key field "remains configured
`Hidden`/read-only exactly as before (DR-QPB-005/FR-QPB-057), unchanged by this criterion." That
half is already covered by the pre-existing `test_ac012_uuid_field_is_autogenerated_and_not_
normally_editable` in `test_qgis_project_config.py` and is not re-asserted here; this file covers
only the new "no alias set" half this criterion adds.

See HARNESS_CONTRACT.md's new "Decision Log D-56/D-57/D-58" section, function 12
(`inspect_field_aliases`), for why a dedicated PyQGIS-backed harness function is used here rather
than a raw `.qgs` XML regex (unlike AC-QPB-013's `RelationReference` check) — the exact QGIS
project-XML `<aliases>` block shape was not independently confirmed against a live QGIS instance,
per this project's hard QGIS-isolation rule barring the test-designer from constructing a
`QgsApplication` for any verification purpose; the judgment is delegated to the harness function's
own real-PyQGIS-backed implementation, mirroring the established `inspect_identification_widget`
precedent (HARNESS_CONTRACT.md function 10).

**Corrected by a later `test-designer` round (2026-08-26; Decision Log D-59).** An earlier version
of `test_every_layer_field_is_accounted_for_by_exactly_one_alias_expectation` (below) incorrectly
assumed the hidden GeoPackage physical primary key `fid` is never a member of `layer.fields()`, the
same way geometry columns genuinely are never members of it — and therefore never accounted for
`fid`'s real presence, causing that test to fail against a real generated project
(`extra=['fid']`). Decision Log D-59 confirms `fid` *is* a genuine member of `layer.fields()` for
every generated GeoPackage layer, but correctly receives no Korean alias, for a different reason
than the UUID primary key's own DR-QPB-071 exclusion: it is excluded from the *visible*
attribute-editor form tree by the pre-existing, unrelated `_build_drag_and_drop_form` mechanism
(`qfield_builder/qgis_worker.py`), not because it is absent from the layer's field collection. The
completeness test below is corrected accordingly to treat `fid` as a third, distinct field
category — present, no alias, and out of DR-QPB-071/Section 8.5's alias-proposal scope entirely
(neither the table's own UUID primary key nor an in-scope aliased field). The 73
`test_ac098_in_scope_field_has_the_exact_confirmed_korean_alias` and 15
`test_ac098_uuid_primary_key_field_has_no_alias_set` cases below are unaffected by this
correction — neither ever asserted anything about `fid`. See
`../qfield_project_builder_korean_field_aliases.traceability.md`'s correction note for the full
record.

Every project used below is built via the ordinary, `identification_enabled=False`
`built_project_by_type` fixture (this suite's existing default): the reserved,
inactive-until-post-MVP columns Section 8.5 also assigns an alias to (`selected_ktsn`,
`identification_score`, `occurrence_probability`, `identification_timestamp`,
`identification_model_version`) are already part of every survey type's schema regardless of
`identification_enabled` (DR-QPB-034/052/053 — "must remain nullable and inactive in the MVP
build", not "must not exist unless the post-MVP feature is enabled"; the pre-existing
`test_type1_layer_has_exactly_three_relation_free_photo_fields` in
`test_geopackage_schema_by_type.py` already relies on this same fact for the photo columns), so no
special build configuration is needed to exercise their aliases here.
"""
from __future__ import annotations

import pytest

from .conftest import FID_PHYSICAL_KEY_FIELD, KOREAN_FIELD_ALIASES

pytestmark = pytest.mark.qgis


def _in_scope_field_cases():
    cases = []
    ids = []
    for survey_type, tables in KOREAN_FIELD_ALIASES.items():
        for table, table_info in tables.items():
            for field, alias in table_info["aliases"].items():
                cases.append((survey_type, table, field, alias))
                ids.append(f"{survey_type}-{table}-{field}")
    return cases, ids


def _uuid_pk_cases():
    cases = []
    ids = []
    for survey_type, tables in KOREAN_FIELD_ALIASES.items():
        for table, table_info in tables.items():
            cases.append((survey_type, table, table_info["uuid_pk"]))
            ids.append(f"{survey_type}-{table}")
    return cases, ids


def _table_cases():
    cases = []
    ids = []
    for survey_type, tables in KOREAN_FIELD_ALIASES.items():
        for table in tables:
            cases.append((survey_type, table))
            ids.append(f"{survey_type}-{table}")
    return cases, ids


_IN_SCOPE_FIELD_CASES, _IN_SCOPE_FIELD_IDS = _in_scope_field_cases()
_UUID_PK_CASES, _UUID_PK_IDS = _uuid_pk_cases()
_TABLE_CASES, _TABLE_IDS = _table_cases()


# --- AC-QPB-098 (positive half: every in-scope field carries its exact confirmed Korean alias) --

@pytest.mark.parametrize(
    "survey_type,table,field,expected_alias", _IN_SCOPE_FIELD_CASES, ids=_IN_SCOPE_FIELD_IDS
)
def test_ac098_in_scope_field_has_the_exact_confirmed_korean_alias(
    inspect_field_aliases, built_project_by_type, survey_type, table, field, expected_alias
):
    result = built_project_by_type(survey_type)
    assert result["success"], result.get("error_message")

    info = inspect_field_aliases(result["project_dir"], table)
    assert field in info["field_names"], (
        f"{survey_type}.{table}.{field} not found on the generated layer's own field list "
        f"({info['field_names']!r})"
    )
    actual_alias = info["aliases"].get(field)
    assert actual_alias == expected_alias, (
        f"{survey_type}.{table}.{field} alias mismatch: expected {expected_alias!r} "
        f"(Section 8.5; Decision Log D-56/D-57/D-58), got {actual_alias!r}"
    )
    assert actual_alias != field, (
        f"{survey_type}.{table}.{field} alias must not be the raw snake_case column name "
        f"(FR-QPB-119)"
    )


# --- AC-QPB-098 (negative half: a table's own UUID primary key carries no alias at all) ---------

@pytest.mark.parametrize("survey_type,table,uuid_pk_field", _UUID_PK_CASES, ids=_UUID_PK_IDS)
def test_ac098_uuid_primary_key_field_has_no_alias_set(
    inspect_field_aliases, built_project_by_type, survey_type, table, uuid_pk_field
):
    result = built_project_by_type(survey_type)
    assert result["success"], result.get("error_message")

    info = inspect_field_aliases(result["project_dir"], table)
    assert uuid_pk_field in info["field_names"], (
        f"{survey_type}.{table}.{uuid_pk_field} (the table's own UUID primary key) not found on "
        f"the generated layer's own field list ({info['field_names']!r})"
    )
    actual_alias = info["aliases"].get(uuid_pk_field)
    assert not actual_alias, (
        f"{survey_type}.{table}.{uuid_pk_field} is a UUID field in its primary-key role "
        f"(DR-QPB-071) and must have no alias set — a Korean label for a field a surveyor never "
        f"sees in the form would be meaningless — but got {actual_alias!r}"
    )


# --- AC-QPB-098 (completeness: no unaccounted-for field silently escapes the three expectations) -

@pytest.mark.parametrize("survey_type,table", _TABLE_CASES, ids=_TABLE_IDS)
def test_every_layer_field_is_accounted_for_by_exactly_one_alias_expectation(
    inspect_field_aliases, built_project_by_type, survey_type, table
):
    """Belt-and-suspenders completeness check: every field this harness reports for a layer falls
    into exactly one of three expectations —

    1. the table's own UUID primary key (expected: no alias, per the negative test above);
    2. one of Section 8.5's explicitly listed in-scope fields (expected: its confirmed alias, per
       the positive test above); or
    3. the GeoPackage physical primary key `fid` (expected: present, but no alias, and out of
       DR-QPB-071/Section 8.5's alias-proposal scope entirely — a different, unrelated reason than
       category 1's "meaningless label for a hidden field" reasoning; see Decision Log D-59) —

    never a fourth, genuinely unaccounted-for field silently missing an alias expectation of any
    kind. This is what makes AC-QPB-098's own "every field ... except a table's own UUID primary
    key" wording fully covered, rather than only covering the specific fields this test-design
    round happened to enumerate.

    `fid` (category 3) is deliberately not folded into category 1 or 2: it is not a UUID field at
    all (so it cannot be "the table's own UUID primary key"), and Section 8.5 never proposed a
    Korean alias for it (so it cannot be "an in-scope aliased field") — DR-QPB-071/Section 8.5's
    own scoping note excludes it from the alias proposal for a reason specific to it alone
    (Decision Log D-59). An earlier version of this test incorrectly assumed `fid` is never a
    member of `layer.fields()` in the first place (the same way geometry columns genuinely are
    never members of it) and so never accounted for it at all here, which failed against a real
    generated project with `extra=['fid']` — see this file's module docstring and this round's
    traceability file for the full correction record.
    """
    result = built_project_by_type(survey_type)
    assert result["success"], result.get("error_message")

    table_info = KOREAN_FIELD_ALIASES[survey_type][table]
    expected_fields = set(table_info["aliases"]) | {table_info["uuid_pk"], FID_PHYSICAL_KEY_FIELD}

    info = inspect_field_aliases(result["project_dir"], table)
    actual_fields = set(info["field_names"])
    assert actual_fields == expected_fields, (
        f"{survey_type}.{table}: the layer's actual field set does not match Section 8.5's own "
        f"per-table field list plus the physical `fid` primary key (Decision Log D-59). "
        f"missing={sorted(expected_fields - actual_fields)!r} "
        f"extra={sorted(actual_fields - expected_fields)!r} — an 'extra' field here is one this "
        f"test-design round did not assign any alias expectation to at all (none of the "
        f"UUID-primary-key 'no alias' expectation, an in-scope confirmed-alias expectation, or "
        f"`fid`'s own distinct 'present, no alias, out of scope' expectation), which would leave "
        f"AC-QPB-098 only partially covered for this table if left unnoticed"
    )

    # `fid` (category 3 above) genuinely is present on the layer (Decision Log D-59), but it must
    # still carry no alias — assert this directly rather than only accounting for its bare
    # presence above, so this completeness check would still fail if a stray alias were ever set
    # on it.
    fid_alias = info["aliases"].get(FID_PHYSICAL_KEY_FIELD)
    assert not fid_alias, (
        f"{survey_type}.{table}.{FID_PHYSICAL_KEY_FIELD} (the GeoPackage physical primary key; "
        f"DR-QPB-071/Decision Log D-59) is out of Section 8.5's alias-proposal scope and must "
        f"have no alias set, but got {fid_alias!r}"
    )
