"""Acceptance coverage for AC-FBKR-001..007.

AC-FBKR-002..007 supply mocked QGIS provider data to the shipped QML collector and
then inspect the HTML generated by that collector in a Node DOM runtime. The fixture
is deliberately not a second report-input or report-output model.
"""

from __future__ import annotations

import copy
import json
from collections.abc import Iterable
from typing import Any

import pytest


IOS_SANDBOX_PATH = "/var/mobile/Containers/Data/Application/7F93A3E1-TEST/project.gpkg"
_FAKE_VWORLD_KEY = "ACCEPTANCE-ONLY-VWORLD-KEY-NOT-A-SECRET"


@pytest.fixture()
def render_html_report_refresh_fixture(acceptance_api):
    renderer = getattr(acceptance_api, "render_html_report_refresh_fixture", None)
    if renderer is None:
        pytest.skip(
            "qfield_builder.acceptance_api.render_html_report_refresh_fixture() is not "
            "implemented yet — see tests/acceptance/qfield_project_builder/HARNESS_CONTRACT.md"
        )
    return renderer


def _run(renderer, fixture: dict[str, Any]) -> dict[str, Any]:
    # These names identify the retired abstract/Python-model fixture contract. A bridge that
    # accepts them can silently avoid exercising the QML provider reads and generated HTML.
    forbidden = {"source_columns", "source_rows", "spatial_records", "anchor_contexts", "analytics_input"}
    assert not (forbidden & fixture.keys())
    original = copy.deepcopy(fixture)
    result = renderer(fixture)
    assert fixture == original, "QGIS collection and report rendering must be read-only"
    assert result["success"] is True, result.get("error_message")
    assert result["bridge"]["qml"]["qpb_build_html_report_called"] is True
    assert result["bridge"]["html"]["generated_from_qpb_build_html_report"] is True
    return result


def _payload(result: dict[str, Any]) -> dict[str, Any]:
    """The actual qpbLastReportPayload, serialized by the QML runtime after collection."""
    return result["bridge"]["qml"]["report_payload"]


def _html(result: dict[str, Any]) -> dict[str, Any]:
    """DOM observations from the scripts embedded in that exact generated HTML."""
    return result["bridge"]["html"]["document"]


def _geometry_by_uuid(result: dict[str, Any]) -> dict[str, dict[str, Any]]:
    records: dict[str, dict[str, Any]] = {}
    for table in _payload(result)["tables"]:
        for record in table.get("records", []):
            records[str(record["uuid"])] = record["geometry"]
    return records


def _coordinate_vectors(geometry: Any) -> Iterable[list[Any]]:
    if isinstance(geometry, dict):
        if "coordinates" in geometry:
            yield from _coordinate_vectors(geometry["coordinates"])
        for key, value in geometry.items():
            if key != "coordinates":
                yield from _coordinate_vectors(value)
    elif isinstance(geometry, list):
        if geometry and all(not isinstance(value, (dict, list)) for value in geometry):
            yield geometry
        else:
            for value in geometry:
                yield from _coordinate_vectors(value)


def _assert_xy_only(geometry: dict[str, Any]) -> None:
    vectors = list(_coordinate_vectors(geometry))
    assert vectors, "valid GeoJSON must contain coordinate vectors"
    assert all(len(vector) == 2 for vector in vectors), geometry


def _feature(attributes: dict[str, Any], geometry: dict[str, Any] | None) -> dict[str, Any]:
    """A QGIS feature mock: attributes plus a runtime QgsGeometry-method descriptor."""
    return {"attributes": attributes, "geometry": geometry}


def _layer(
    name: str,
    fields: list[str],
    features: list[dict[str, Any]],
    *,
    geometry_column: str | None = None,
    geometry_type: str | None = None,
    crs: str = "EPSG:4326",
) -> dict[str, Any]:
    return {
        "name": name,
        "fields": fields,
        "geometry_column": geometry_column,
        "geometry_type": geometry_type,
        "crs_authid": crs,
        "features": features,
    }


def _project_fixture(survey_type: str, *, direct_available: bool) -> dict[str, Any]:
    return {
        "qgis_provider": {
            "project": {"survey_type": survey_type, "project_slug": "acceptance-report"},
            "direct_gpkg": {"available": direct_available, "failure": "SQLite bridge unavailable"},
            "loaded_layers": [],
            "runtime_capabilities": {"coordinate_transform": False},
        },
        "html_runtime": {"network_available": False, "viewport_widths": [375, 1280]},
    }


def _direct_tables(layers: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Translate QGIS feature mocks to unclassified direct GeoPackage SQL rows."""
    tables = []
    for layer in layers:
        rows = []
        for feature in layer["features"]:
            row = dict(feature["attributes"])
            geometry = feature.get("geometry")
            if layer["geometry_column"] is not None:
                row[layer["geometry_column"]] = (
                    None
                    if geometry is None or geometry.get("isNull") or geometry.get("isEmpty")
                    else geometry.get("asJson", {}).get("return", "invalid-wkb")
                )
            rows.append(row)
        columns = list(layer["fields"])
        if layer["geometry_column"] is not None:
            columns.append(layer["geometry_column"])
        tables.append({
            "name": layer["name"], "columns": columns,
            "geometry_column": layer["geometry_column"], "geometry_type": layer["geometry_type"],
            "srs_id": layer["crs_authid"], "rows": rows,
        })
    return tables


def _type1_geometry_fixture(collection_path: str) -> dict[str, Any]:
    fixture = _project_fixture("simple_inventory", direct_available=collection_path == "direct")
    fields = ["inventory_id", "observed_at", "surveyor", "selected_korean_name", "selected_ktsn", "notes"]
    geometries = {
        "inv-valid": {"isNull": False, "isEmpty": False, "asJson": {"return": {"type": "Point", "coordinates": [127.123, 37.456, 999.5, 123.25]}}},
        "inv-empty": {"isNull": False, "isEmpty": True},
        "inv-serializer": {"isNull": False, "isEmpty": False, "asJson": {"throw": "asJson unavailable"}, "asWkb": {"throw": "WKB unavailable"}},
        "inv-unknown-crs": {"isNull": False, "isEmpty": False, "asJson": {"return": {"type": "Point", "coordinates": [1, 2]}}},
        "inv-malformed": {"isNull": False, "isEmpty": False, "asJson": {"return": {"type": "Point", "coordinates": ["not-x", 37.5, 50, 60]}}},
    }
    attributes = {
        uuid: {"inventory_id": uuid, "observed_at": "2026-09-04", "surveyor": "현장 조사자", "selected_korean_name": "검증종", "selected_ktsn": "KTSN-001", "notes": "원본 행 유지"}
        for uuid in geometries
    }
    fixture["qgis_provider"]["loaded_layers"] = [
        _layer("inventory_observation", fields, [_feature(attributes[uuid], geometry) for uuid, geometry in geometries.items()], geometry_column="geom", geometry_type="POINT")
    ]
    # SQL mock rows retain the real declared geometry column, not a pre-classified report result.
    fixture["qgis_provider"]["direct_gpkg"]["tables"] = [{
        "name": "inventory_observation", "geometry_column": "geom", "geometry_type": "POINT", "srs_id": 4326,
        "columns": fields + ["geom"],
        "rows": [
            dict(attributes[uuid], geom=(None if uuid == "inv-empty" else geometry["asJson"].get("return", "invalid-wkb")))
            for uuid, geometry in geometries.items()
        ],
    }]
    if collection_path == "direct":
        rows = fixture["qgis_provider"]["direct_gpkg"]["tables"][0]["rows"]
        rows[2]["geom"] = "invalid-wkb"
        rows[3]["geom"] = {"type": "Point", "coordinates": [1, 2]}
        rows[4]["geom"] = {"type": "Point", "coordinates": ["not-x", 37.5, 50, 60]}
        fixture["qgis_provider"]["direct_gpkg"]["row_crs_overrides"] = {
            "inv-valid": "EPSG:4326", "inv-empty": "EPSG:4326", "inv-serializer": "EPSG:4326",
            "inv-unknown-crs": "UNKNOWN:LOCAL", "inv-malformed": "EPSG:4326",
        }
    else:
        fixture["qgis_provider"]["loaded_layers"][0]["features"][3]["layer_crs_authid"] = "UNKNOWN:LOCAL"
    return fixture


@pytest.mark.parametrize("collection_path", ["direct", "fallback"])
def test_ac002_provider_geometry_outcomes_are_distinct_and_xy_only(
    render_html_report_refresh_fixture, collection_path
):
    """FR-FBKR-001..004 through qpbGeometryToGeoJson/qpbCollectGpkgSpatialRows."""
    result = _run(render_html_report_refresh_fixture, _type1_geometry_fixture(collection_path))
    by_uuid = _geometry_by_uuid(result)
    assert {uuid: value["outcome"] for uuid, value in by_uuid.items()} == {
        "inv-valid": "valid", "inv-empty": "actual_empty", "inv-serializer": "serialization_failure",
        "inv-unknown-crs": "transform_failure", "inv-malformed": "malformed_xy",
    }
    valid = by_uuid["inv-valid"]
    assert valid["geojson"] == {"type": "Point", "coordinates": [127.123, 37.456]}
    _assert_xy_only(valid["geojson"])
    assert _html(result)["map"]["feature_anchor_uuids"] == ["inv-valid"]
    assert all(value["reason"] for value in by_uuid.values())
    assert _html(result)["csv"]["all_row_uuids"] == sorted(by_uuid)


def _anchor_fixture(survey_type: str, collection_path: str) -> tuple[dict[str, Any], list[str], str]:
    fixture = _project_fixture(survey_type, direct_available=collection_path == "direct")
    point = lambda x, y: {"isNull": False, "isEmpty": False, "asJson": {"return": {"type": "Point", "coordinates": [x, y]}}}
    polygon = {"isNull": False, "isEmpty": False, "asJson": {"return": {"type": "MultiPolygon", "coordinates": [[[[127.0, 37.0], [127.01, 37.0], [127.01, 37.01], [127.0, 37.0]]]]}}}
    layers = {
        "site": _layer("site", ["site_id", "site_name"], [_feature({"site_id": "site-01", "site_name": "조사지 A"}, polygon)], geometry_column="site_geom", geometry_type="MULTIPOLYGON"),
        "survey": _layer("survey", ["survey_id", "site_id", "plot_id", "survey_date", "surveyor"], [_feature({"survey_id": "survey-01", "site_id": "site-01", "plot_id": "plot-01", "survey_date": "2026-09-04", "surveyor": "조사자"}, point(127.2, 37.2))], geometry_column="plot_geom", geometry_type="POINT"),
        "plot": _layer("plot", ["plot_id", "site_id", "plot_name"], [_feature({"plot_id": "plot-01", "site_id": "site-01", "plot_name": "영구 조사구"}, {"isNull": False, "isEmpty": True})], geometry_column="plot_geom", geometry_type="POINT"),
        "observation": _layer("observation", ["observation_id", "survey_id", "selected_korean_name", "selected_scientific_name", "selected_ktsn", "cover", "notes"], [_feature({"observation_id": "observation-01", "survey_id": "survey-01", "selected_korean_name": "관찰종", "selected_scientific_name": "Observed sp.", "selected_ktsn": "KTSN-OBS", "cover": 10, "notes": "관찰 비고", "attribute_coordinates": [111, 11], "photo_gps": [112, 12], "nearby_geometry": {"type": "Point", "coordinates": [110, 10]}}, None)]),
        "inventory_observation": _layer("inventory_observation", ["inventory_id", "observed_at", "surveyor", "selected_korean_name", "selected_ktsn"], [_feature({"inventory_id": "inventory-01", "observed_at": "2026-09-04", "surveyor": "조사자", "selected_korean_name": "가시나무", "selected_ktsn": "KTSN-INV"}, point(120, 30))], geometry_column="geom", geometry_type="POINT"),
        "community": _layer("community", ["community_id", "survey_id", "community_name", "dominant_species", "area", "notes"], [_feature({"community_id": "community-01", "survey_id": "survey-01", "community_name": "소나무 군락", "dominant_species": "소나무", "area": 100.0, "notes": "군락 비고"}, polygon)], geometry_column="community_geom", geometry_type="MULTIPOLYGON"),
    }
    active = {
        "simple_inventory": ([layers["inventory_observation"]], ["inventory-01"], "inventory-01"),
        "temporary_plots": ([layers["site"], layers["survey"], layers["observation"]], ["site-01", "survey-01"], "observation-01"),
        "permanent_plots": ([layers["site"], layers["plot"], layers["survey"], layers["observation"]], ["site-01", "plot-01"], "observation-01"),
        "vegetation_mapping": ([layers["site"], layers["survey"], layers["community"]], ["community-01"], "community-01"),
    }[survey_type]
    fixture["qgis_provider"]["loaded_layers"] = active[0]
    fixture["qgis_provider"]["direct_gpkg"]["tables"] = _direct_tables(active[0])
    return fixture, active[1], active[2]


@pytest.mark.parametrize("collection_path", ["direct", "fallback"])
@pytest.mark.parametrize("survey_type", ["simple_inventory", "temporary_plots", "permanent_plots", "vegetation_mapping"])
def test_ac003_provider_fk_joins_preserve_type_anchors_and_rows(
    render_html_report_refresh_fixture, survey_type, collection_path
):
    fixture, expected_anchors, expected_join_uuid = _anchor_fixture(survey_type, collection_path)
    result = _run(render_html_report_refresh_fixture, fixture)
    html = _html(result)
    assert html["map"]["feature_anchor_uuids"] == expected_anchors
    assert html["table"]["joined_row_uuids"] == [expected_join_uuid]
    assert html["csv"]["all_row_uuids"] == [expected_join_uuid]
    features = {feature["anchor_uuid"]: feature for feature in _payload(result)["map_features"]}
    for uuid in expected_anchors:
        _assert_xy_only(features[uuid]["geometry"]["geojson"])
    if survey_type == "temporary_plots":
        assert features["survey-01"]["anchor_table"] == "survey"
        assert "observation-01" not in features
    elif survey_type == "permanent_plots":
        assert features["plot-01"]["anchor_table"] == "plot"
        assert features["plot-01"]["fallback"] == "survey"
        assert features["plot-01"]["geometry"]["geojson"]["coordinates"] == [127.2, 37.2]
        assert "observation-01" not in features
    elif survey_type == "vegetation_mapping":
        assert features["community-01"]["anchor_table"] == "community"
        assert "observation-01" not in features
    rendered_coordinates = [
        vector for feature in features.values()
        for vector in _coordinate_vectors(feature["geometry"]["geojson"])
    ]
    for forbidden_coordinate in ([111, 11], [112, 12], [110, 10]):
        assert forbidden_coordinate not in rendered_coordinates, "non-anchor attributes cannot invent map geometry"


def test_ac004_normal_korean_status_and_closed_diagnostics_are_rendered_by_html_runtime(
    render_html_report_refresh_fixture,
):
    fixture, _, _ = _anchor_fixture("simple_inventory", "fallback")
    fixture["qgis_provider"]["direct_gpkg"] = {"available": False, "failure": "SQLite bridge unavailable", "location": IOS_SANDBOX_PATH}
    fixture["qgis_provider"]["loaded_layers"][0]["features"][0]["attributes"]["notes"] = "현장 기록"
    result = _run(render_html_report_refresh_fixture, fixture)
    html = _html(result)
    assert html["diagnostics"]["closed_by_default"] is True
    assert html["diagnostics"]["keyboard_operable"] is True
    assert "수집" in html["normal"]["status_text"]
    assert "전체 수집 완료" not in html["normal"]["status_text"]
    assert "inventory_observation" not in html["normal"]["text"]
    assert html["diagnostics"]["claims_complete_direct_inventory"] is False
    _assert_private_values_absent(result)


def test_ac005_provider_joined_notes_are_korean_deduplicated_and_private_values_do_not_render(
    render_html_report_refresh_fixture,
):
    fixture, _, _ = _anchor_fixture("temporary_plots", "fallback")
    survey = fixture["qgis_provider"]["loaded_layers"][1]["features"][0]["attributes"]
    observation = fixture["qgis_provider"]["loaded_layers"][2]["features"][0]["attributes"]
    survey["notes"] = "조사 메모"; observation["notes"] = "관찰 메모"
    observation["leaf_photo_path"] = IOS_SANDBOX_PATH
    result = _run(render_html_report_refresh_fixture, fixture)
    html = _html(result)
    fields = html["table"]["rows"][0]["fields"]
    assert {(field["label"], field["value"]) for field in fields if "비고" in field["label"]} == {
        ("관찰 비고", "관찰 메모"), ("조사 비고", "조사 메모")
    }
    normal_blob = json.dumps(html["normal"], ensure_ascii=False)
    assert "observation_id" not in normal_blob and "survey_id" not in normal_blob
    _assert_private_values_absent(result)

    equal_fixture, _, _ = _anchor_fixture("temporary_plots", "fallback")
    equal_fixture["qgis_provider"]["loaded_layers"][1]["features"][0]["attributes"]["notes"] = "동일 메모"
    equal_fixture["qgis_provider"]["loaded_layers"][2]["features"][0]["attributes"]["notes"] = "동일 메모"
    equal_fields = _html(_run(render_html_report_refresh_fixture, equal_fixture))["table"]["rows"][0]["fields"]
    assert [(field["label"], field["value"]) for field in equal_fields if "비고" in field["label"]] == [
        ("비고", "동일 메모")
    ]


@pytest.mark.parametrize(
    ("survey_type", "expected_cards"),
    [
        ("simple_inventory", {"species_occurrence"}),
        ("temporary_plots", {"species_occurrence", "mean_cover"}),
        ("permanent_plots", {"species_occurrence", "mean_cover"}),
        ("vegetation_mapping", {"community_area", "community_composition"}),
        ("vegetation_mapping", set()),
    ],
)
def test_ac006_chart_cards_are_derived_from_provider_attributes_not_analytics_input(
    render_html_report_refresh_fixture, survey_type, expected_cards
):
    fixture, _, _ = _anchor_fixture(survey_type, "fallback")
    if survey_type != "vegetation_mapping":
        observation_layer = next(
            layer for layer in fixture["qgis_provider"]["loaded_layers"]
            if layer["name"] in {"inventory_observation", "observation"}
        )
        primary_key = "inventory_id" if survey_type == "simple_inventory" else "observation_id"
        observation_layer["features"].append(_feature({
            primary_key: f"{survey_type}-ktsn-only", "survey_id": "survey-01",
            "selected_ktsn": "KTSN-ONLY", "cover": None,
        }, None))
    if survey_type == "permanent_plots":
        fixture["qgis_provider"]["loaded_layers"][-1]["features"][0]["attributes"]["cover"] = "bad"
        fixture["qgis_provider"]["loaded_layers"][-1]["features"].append(_feature({"observation_id": "observation-02", "survey_id": "survey-01", "selected_korean_name": "관찰종", "cover": 20}, None))
    if survey_type == "vegetation_mapping" and not expected_cards:
        community = fixture["qgis_provider"]["loaded_layers"][-1]["features"][0]["attributes"]
        community["area"] = "bad"; community["dominant_species"] = ""
    result = _run(render_html_report_refresh_fixture, fixture)
    analytics = _html(result)["analytics"]
    assert {card["kind"] for card in analytics["cards"]} == expected_cards
    assert analytics["section_visible"] is bool(expected_cards)
    assert analytics["toc_entry_visible"] is bool(expected_cards)
    for card in analytics["cards"]:
        assert any("가" <= char <= "힣" for char in card["title_ko"])
        assert any("가" <= char <= "힣" for char in card["basis_ko"])
        assert card["text_equivalent"]
        assert card["keyboard_operable"] is True
        assert card["focus_indicator_visible"] is True
        assert card["print_text_equivalent_visible"] is True
        assert "KTSN-ONLY" not in json.dumps(card["text_equivalent"], ensure_ascii=False)
    assert all(not viewport["page_horizontal_overflow"] for viewport in analytics["viewports"])


def test_ac007_generated_html_retains_local_interactions_with_osm_fallback_without_vworld(
    render_html_report_refresh_fixture,
):
    fixture, _, _ = _anchor_fixture("simple_inventory", "fallback")
    layer = fixture["qgis_provider"]["loaded_layers"][0]
    layer["features"].append(_feature({"inventory_id": "inventory-02", "observed_at": "2026-09-04", "surveyor": "조사자", "selected_korean_name": "나", "selected_ktsn": "KTSN-2"}, {"isNull": False, "isEmpty": False, "asJson": {"return": {"type": "Point", "coordinates": [127.1, 37.1]}}}))
    fixture["html_runtime"].update({
        # A standalone report must ignore any provider runtime key: it may not serialize or
        # inject it, and it must use the OSM fallback without a VWorld control.
        "runtime_vworld_key": _FAKE_VWORLD_KEY,
        "prefers_reduced_motion": True,
        "actions": ["filter:가", "keyboard_sort:selected_korean_name:descending", "theme:dark", "open_diagnostics", "print", "csv:all", "csv:filtered"],
    })
    result = _run(render_html_report_refresh_fixture, fixture)
    html = _html(result)
    assert html["controls"]["vworld_visible"] is False
    assert html["controls"]["vworld_key_embedded"] is False
    assert "OpenStreetMap" in html["normal"]["text"]
    assert html["interactions"]["local_operations_used_network"] is False
    assert html["interactions"]["keyboard_table_sort_operable"] is True
    assert html["interactions"]["diagnostics_operable"] is True
    assert html["interactions"]["theme"] == "dark"
    assert html["interactions"]["reduced_motion"] is True
    assert html["interactions"]["print_diagnostics_included"] is False
    assert html["csv"]["all_row_uuids"] == ["inventory-01", "inventory-02"]
    assert html["csv"]["filtered_row_uuids"] == ["inventory-01"]
    assert _FAKE_VWORLD_KEY not in json.dumps(result, ensure_ascii=False)


def _assert_private_values_absent(result: dict[str, Any]) -> None:
    rendered = json.dumps(result["bridge"]["html"], ensure_ascii=False, default=str)
    assert "/var/mobile/Containers/" not in rendered
    assert "7F93A3E1-TEST" not in rendered
    assert _FAKE_VWORLD_KEY not in rendered


@pytest.mark.device
@pytest.mark.manual
@pytest.mark.skip(
    reason=(
        "AC-FBKR-001 requires a physical iPhone running QField 4.2.4 and cannot be passed by "
        "the Node/QML provider bridge. Manual QA: install a Type 1 fixture with exactly three "
        "known non-empty EPSG:4326 inventory_observation points; make direct GeoPackage SQLite "
        "unavailable while the permitted loaded-layer fallback remains active; generate and open "
        "the local HTML. Verify all three points at their recorded XY locations, no actual-empty "
        "label caused only by direct-path failure, a Korean limited/unverified normal collection "
        "status, and closed then open Diagnostics showing fallback and outcome counts. Record only "
        "fixture identifier, device model, iOS/QField versions, report timestamp, visible point "
        "count, and redacted screenshots of map plus closed/open Diagnostics. Do not include API "
        "keys, credentials, photos, UUIDs, iOS sandbox paths, or other personal/project-identifying "
        "paths. Desktop, QGIS, simulator, Node, or browser results cannot pass this criterion."
    )
)
def test_ac001_iphone_qfield_loaded_layer_geometry_gate_requires_privacy_safe_manual_evidence():
    raise AssertionError("should never run while skipped — see skip reason")


@pytest.mark.parametrize("collection_path", ["direct", "fallback"])
@pytest.mark.parametrize("survey_type", ["simple_inventory", "temporary_plots", "permanent_plots", "vegetation_mapping"])
def test_report_csv_uses_visible_columns_and_authoritative_wgs84_points(
    render_html_report_refresh_fixture, survey_type, collection_path
):
    import csv
    import io

    fixture, _, _ = _anchor_fixture(survey_type, collection_path)
    fixture["html_runtime"]["actions"] = ["csv:all"]
    # CSV must remain rectangular when user data contains delimiters, quotes and newlines.
    leaf = {"simple_inventory": "inventory_observation", "vegetation_mapping": "community"}.get(
        survey_type, "observation"
    )
    layers = fixture["qgis_provider"]["loaded_layers"]
    layer = next(item for item in layers if item["name"] == leaf)
    if "notes" not in layer["fields"]:
        layer["fields"].append("notes")
    note = '메모, "인용"\n다음 줄'
    layer["features"][0]["attributes"]["notes"] = note
    duplicate = copy.deepcopy(layer["features"][0])
    uuid_field = {"inventory_observation": "inventory_id", "community": "community_id"}.get(leaf, "observation_id")
    duplicate["attributes"][uuid_field] += "-second"
    layer["features"].append(duplicate)
    fixture["qgis_provider"]["direct_gpkg"]["tables"] = _direct_tables(layers)
    result = _run(render_html_report_refresh_fixture, fixture)
    payload = _payload(result)
    primary_text = result["bridge"]["qml"]["csv_text"]
    primary = list(csv.reader(io.StringIO(primary_text.lstrip("\ufeff"), newline="")))
    browser_text = _html(result)["csv"]["downloads"][0]
    browser = list(csv.reader(io.StringIO(browser_text.lstrip("\ufeff"), newline="")))
    assert primary == browser
    assert len(primary) == 3  # Two observations sharing parents must remain two rows.
    headers = primary[0]
    assert len(headers) == len(set(headers))
    assert all(len(row) == len(headers) for row in primary)
    assert not any("UUID" in h or "무결성" in h or "__" in h for h in headers)
    assert all(note in row for row in primary[1:])
    assert [column["label"] for column in payload["columns"]] == headers
    assert [f["label"] for f in _html(result)["table"]["rows"][0]["fields"]] == headers
    if survey_type == "vegetation_mapping":
        assert "위도 (WGS84)" not in headers and "경도 (WGS84)" not in headers
    else:
        latitude, longitude = ((30, 120) if survey_type == "simple_inventory" else (37.2, 127.2))
        for row in primary[1:]:
            assert row[headers.index("위도 (WGS84)")] == f"{latitude:.8f}"
            assert row[headers.index("경도 (WGS84)")] == f"{longitude:.8f}"
    if survey_type != "simple_inventory":
        assert headers.count("조사지") == 1 and headers.count("조사일자") == 1
        assert all(row[headers.index("조사지")] == "조사지 A" for row in primary[1:])


def test_point_coordinates_follow_plot_geometry_and_do_not_rescue_missing_geometry(
    render_html_report_refresh_fixture,
):
    fixture, _, _ = _anchor_fixture("permanent_plots", "direct")
    layers = fixture["qgis_provider"]["loaded_layers"]
    plot = next(layer for layer in layers if layer["name"] == "plot")
    plot["features"][0]["geometry"] = {
        "isNull": False, "isEmpty": False,
        "asJson": {"return": {"type": "Point", "coordinates": [128.12345678, 36.87654321, 50]}},
    }
    fixture["qgis_provider"]["direct_gpkg"]["tables"] = _direct_tables(layers)
    result = _run(render_html_report_refresh_fixture, fixture)
    values = _payload(result)["joined"][0]["values"]
    assert values["report__latitude"] == "36.87654321"
    assert values["report__longitude"] == "128.12345678"
    # If plot and survey geometry are missing, nearby site polygons cannot invent a coordinate.
    for layer in layers:
        if layer["name"] in {"plot", "survey"}:
            layer["features"][0]["geometry"] = None
    fixture["qgis_provider"]["direct_gpkg"]["tables"] = _direct_tables(layers)
    result = _run(render_html_report_refresh_fixture, fixture)
    values = _payload(result)["joined"][0]["values"]
    assert not values.get("report__latitude") and not values.get("report__longitude")
    assert len(_payload(result)["joined"]) == 1


def test_missing_parent_diagnostic_survives_removal_of_integrity_column(
    render_html_report_refresh_fixture,
):
    fixture, _, _ = _anchor_fixture("temporary_plots", "fallback")
    next(layer for layer in fixture["qgis_provider"]["loaded_layers"] if layer["name"] == "site")["features"] = []
    result = _run(render_html_report_refresh_fixture, fixture)
    payload = _payload(result)
    assert len(payload["joined"]) == 1
    assert "missing parent: site" in payload["joined"][0]["integrity"]
    assert payload["summary_stats"]["orphanCount"] == 1
    assert all(column["source_field"] != "integrity" for column in payload["columns"])


def test_untransformable_projected_point_does_not_export_metres_as_degrees(
    render_html_report_refresh_fixture,
):
    fixture, _, _ = _anchor_fixture("simple_inventory", "fallback")
    layer = fixture["qgis_provider"]["loaded_layers"][0]
    layer["crs_authid"] = "EPSG:3857"
    layer["features"][0]["geometry"]["asJson"]["return"]["coordinates"] = [14137575, 4495009]
    result = _run(render_html_report_refresh_fixture, fixture)
    row = _payload(result)["joined"][0]
    assert not row["values"].get("report__latitude")
    assert not row["values"].get("report__longitude")
    assert _geometry_by_uuid(result)["inventory-01"]["valid"] is False
